name: Code check

on: [ pull_request ]

jobs:
  analysis:
    name: static code analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.3"
          - "8.4"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
        env:
          fail-fast: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: "highest"
          composer-options: --optimize-autoloader

      - name: PHP CodeSniffer
        run: vendor/bin/phpcs

      - name: Psalm
        run: vendor/bin/psalm --stats --output-format=github

      - name: PHPStan
        run: vendor/bin/phpstan analyse
